---
- name: Deploy and manage Podman containers
  hosts: podman
  become: true
  roles:
    - role: podman
      vars:
        podman_containers:
          - name: nginx
            image: docker.io/library/nginx:latest
            ports:
              - "8888:80"
            generate_systemd: true

          - name: redis
            image: docker.io/library/redis:alpine
            state: started
            generate_systemd: true
