# /etc/containers/registries.conf
unqualified-search-registries = ["docker.io", "quay.io", "registry.fedoraproject.org"]

[[registry]]
location = "docker.io"
insecure = false

[[registry]]
location = "quay.io"
insecure = false

[[registry]]
location = "registry.fedoraproject.org"
insecure = false
